---
- name: call an API endpoint
  hosts: localhost
  gather_facts: false
  tasks:
  - name: ping the API
    uri:
      url: https://api.labo.ovh/anything
      body:
        message: "Hello world"
      body_format: json 
      method: POST
      return_content: yes
    register: output
  - name: display output
    debug:
      var: output.content
